### ISSUE TITLE
Wrong instance of POV-Ray

### ISSUE THREAD

**Issue by trevorsandy** [flathub/org.leocad.LeoCAD#14]
https://github.com/flathub/org.leocad.LeoCAD/blob/6dab50bbe9acabc09d657448061cf298db935472/org.leocad.LeoCAD.json#L31

This is the wrong instance of POV-Ray for LeoCAD. 

Leo authored a modification that added a memory mapped file to allow render progress to be displayed from LeoCAD in real time. This feature is not available in the off-the-shelf instance of POV-Ray.

![Screenshot - 09_05_2021 , 03_52_41](https://user-images.githubusercontent.com/13388970/117558125-8cd1f200-b07a-11eb-9a76-abc2ab57dda7.png)

This is the instance (and commit) you should build for LeoCAD - https://github.com/leozide/povray/commit/c65ef9d0c931c8e7844c3ae403b5a53c881fc33f

Cheers,

**Comment by hfiguiere** [comment]
Weird, Leo did review it: https://github.com/flathub/org.leocad.LeoCAD/pull/10 :-)

Will fix

**Comment by leozide** [comment]
The render preview is disabled on linux because I can't control the distributions and the patch wasn't accepted by the povray team.

**Comment by hfiguiere** [comment]
> The render preview is disabled on linux because I can't control the distributions and the patch wasn't accepted by the povray team.

Is there an easy way to enable it?

**Comment by leozide** [comment]
Maybe `#define LC_POVRAY_MEMORY_MAPPED_FILE 1`, I haven't tried.
