### ISSUE TITLE
"Error starting POV-Ray"

### ISSUE THREAD

**Issue by parkerlreed** [flathub/org.leocad.LeoCAD#18]
Steam Deck
Installed from Flathub

Trying to render a basic scene and it errors out with nothing printed to terminal.

![image](https://user-images.githubusercontent.com/841440/200204180-ee984c2b-d3bd-4a96-8126-a34c38e4e611.png)

**Comment by leozide** [comment]
Have you tried going to the preferences and checking the path to the povray binary is correct?

**Comment by parkerlreed** [comment]
Aha yes. I had to update it from the default /usr/bin/povray to the Flatpak /app/bin/povray. 

I've never used LeoCAD any other way with this so maybe that default needs to be set compile time?

**Comment by hfiguiere** [comment]
In `View > Preferences` you need to set the path of povray to be `/app/bin/povray`.

I'll add a patch for this to be done automatically for new users.



![Image](https://github.com/flathub/org.leocad.LeoCAD/assets/114441/c92a6ee8-82ca-464d-8042-9ad2a25d2356)
